/* ============================================================
   DRAMAKAZE — CONTENT  (generated by build-content.py)
   Sources: DistroKid catalog + Spotify (ISRC match) + Bandcamp + overrides.
   To rebuild: drop fresh results.csv / dramakaze_productions.csv next to
   build-content.py and run `python3 build-content.py`.
     - "aliases": names that roll up to a parent artist.
     - "hidden": true  -> kept in data, hidden everywhere (releases drop too).
     - "signed": true  -> shows on ARTISTS (active roster) page. None signed yet.
     - release "spotify" -> Spotify player; "bandcamp" -> Bandcamp player.
   ============================================================ */

window.DRAMAKAZE = {
  "artists": [
    {
      "id": "dane",
      "name": "Dane",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": "",
      "aliases": [
        "Dane Christopher",
        "dane"
      ]
    },
    {
      "id": "abeltriesherbest",
      "name": "abeltriesherbest",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": "",
      "aliases": [
        "Abel."
      ],
      "hidden": true
    },
    {
      "id": "hush",
      "name": "Hush",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "van-alden",
      "name": "Van Alden",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "pool-surfers",
      "name": "Pool Surfers",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "the-artist-ren",
      "name": "The Artist Ren",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "xglypretty",
      "name": "xglypretty",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "stun-gun",
      "name": "Stun Gun",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "mitchell-dolphin",
      "name": "Mitchell Dolphin",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "lily-lewis",
      "name": "Lily Lewis",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "courtney-govan-and-abel",
      "name": "Courtney Govan and Abel.",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "the-stone-kiefs",
      "name": "The Stone Kiefs",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "my-native-tongue",
      "name": "My Native Tongue",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    },
    {
      "id": "sink-swim",
      "name": "Sink Swim",
      "role": "",
      "bio": "",
      "photo": "",
      "instagram": "",
      "spotify": "",
      "site": ""
    }
  ],
  "releases": [
    {
      "id": "r-534081",
      "title": "Drop the Ball",
      "artist": "Mitchell Dolphin",
      "year": 2026,
      "art": "https://i.scdn.co/image/ab67616d0000b2730aeea33dcacaf236d0fb4ead",
      "spotify": "https://open.spotify.com/album/3HyfMyPFa1smut151Zpj6i",
      "type": "single"
    },
    {
      "id": "r-472313",
      "title": "Once Again",
      "artist": "Mitchell Dolphin",
      "year": 2025,
      "art": "https://i.scdn.co/image/ab67616d0000b273d775d8f4880feb5e5f213ee2",
      "spotify": "https://open.spotify.com/album/26uWKSSQ741ry2EtKsgeno",
      "type": "single"
    },
    {
      "id": "r-364791",
      "title": "willow tree",
      "artist": "The Artist Ren",
      "year": 2024,
      "art": "https://i.scdn.co/image/ab67616d0000b2735c68d2fc9c8b34c348f64fbd",
      "spotify": "https://open.spotify.com/album/7z8PDSmqebIj5QWiryGOa1",
      "type": "EP",
      "tracks": [
        "cloudynight",
        "runway",
        "willow tree"
      ]
    },
    {
      "id": "r-870457",
      "title": "porsche pastor",
      "artist": "abeltriesherbest",
      "year": 2023,
      "art": "https://i.scdn.co/image/ab67616d0000b273c2c577a0c5aca340e5119f0d",
      "spotify": "https://open.spotify.com/album/3w9cDHl5Sc9VE8GTMuEHVd",
      "type": "single"
    },
    {
      "id": "r-166030",
      "title": "i need less of me & more of You.",
      "artist": "xglypretty",
      "year": 2023,
      "art": "https://i.scdn.co/image/ab67616d0000b2730f6e6cd9110ac0c0a952746d",
      "spotify": "https://open.spotify.com/album/4ReJIeiKnU9XwSUp4jGVxi",
      "type": "single"
    },
    {
      "id": "r-353928",
      "title": "what if i were to tell you that... (audio movie)",
      "artist": "abeltriesherbest",
      "year": 2023,
      "art": "https://i.scdn.co/image/ab67616d0000b27319cda1322af8c9a54a47b61a",
      "spotify": "https://open.spotify.com/album/6guHhGU1hKCtVkZneGM4A0",
      "type": "single"
    },
    {
      "id": "r-365644",
      "title": "Love Coma",
      "artist": "The Stone Kiefs",
      "year": 2023,
      "art": "https://i.scdn.co/image/ab67616d0000b273c03e9248c6fe145646739ed7",
      "spotify": "https://open.spotify.com/track/4jn1p60DlIo5PYI71kr00r",
      "type": "single"
    },
    {
      "id": "r-264148",
      "title": "bad christian, music",
      "artist": "xglypretty",
      "year": 2022,
      "art": "https://i.scdn.co/image/ab67616d0000b273f1610a91a53ee6a6a4f40627",
      "spotify": "https://open.spotify.com/album/2MmMHL1EimfZwUfKLn5wpE",
      "type": "album",
      "tracks": [
        "my tv wants me dead",
        "get help.",
        "when i find silence",
        "hands off the kids",
        "souled out",
        "bad christian, music"
      ]
    },
    {
      "id": "r-912110",
      "title": "Under the Bleachers (Expanded Edition)",
      "artist": "The Artist Ren",
      "year": 2022,
      "art": "https://i.scdn.co/image/ab67616d0000b27300be530fe2fbca79ba3f2f6f",
      "spotify": "https://open.spotify.com/album/5xDyoxlzfngKodiEF2UtiP",
      "type": "album",
      "tracks": [
        "The Circus",
        "Radio Nurse",
        "Not The Clones!",
        "meowmeow",
        "sleepstuff",
        ".mp3",
        "Under the Bleachers (Expanded Edition)"
      ]
    },
    {
      "id": "r-370327",
      "title": "songs from the big dumpster",
      "artist": "Abel.",
      "year": 2022,
      "art": "https://i.scdn.co/image/ab67616d0000b2735c1f8b94d999ceb590ed5c6b",
      "spotify": "https://open.spotify.com/album/1Y2boLHJ17Yx7OD8igxTGk",
      "type": "album",
      "tracks": [
        "corduroy 12.16.19 master1",
        "duck sauce 5.24.19 for abbs rough1",
        "deathbed 6.4.19 Rough master 1 (feat. ROUXX)",
        "used me well 1.23.19 rough",
        "maybe im not so kind 11.17.22 rough1",
        "secular 11.15.29 rough master 1",
        "baddy banger 1.11.19 rough1 (feat. dane)",
        "BEN TRUST 12.4.20 rough master 2",
        "rings 11.15.19 rough1",
        "overdose v3 6.1.19 master 1",
        "songs from the big dumpster"
      ]
    },
    {
      "id": "r-640527",
      "title": "shower boy",
      "artist": "Abel.",
      "year": 2022,
      "art": "https://i.scdn.co/image/ab67616d0000b27388b39a44d412757fc4bbd5bd",
      "spotify": "https://open.spotify.com/album/0pLa6IWRykFdlFV9czgIkf",
      "type": "single"
    },
    {
      "id": "r-712167",
      "title": "MEGASTORE",
      "artist": "Stun Gun",
      "year": 2022,
      "art": "https://i.scdn.co/image/ab67616d0000b273eb88fb6a44ad7760ac89cc93",
      "spotify": "https://open.spotify.com/album/0JTNu9t7ViqYp3JUQQhKVe",
      "type": "single"
    },
    {
      "id": "r-663486",
      "title": "Put er Down",
      "artist": "Stun Gun",
      "year": 2022,
      "art": "https://i.scdn.co/image/ab67616d0000b27320e8ff0b47de7fa4601d58e8",
      "spotify": "https://open.spotify.com/album/5ULL5lK6RUB6jcEtnpD9QK",
      "type": "single"
    },
    {
      "id": "r-235157",
      "title": "SPS",
      "artist": "Stun Gun",
      "year": 2022,
      "art": "https://i.scdn.co/image/ab67616d0000b2734dcd39fd41b9122a9919f8c3",
      "spotify": "https://open.spotify.com/album/3D3dIngKf8ngDG2BtnzLNq",
      "type": "single"
    },
    {
      "id": "r-999016",
      "title": "Can't Love You the Way I Hate You",
      "artist": "Abel.",
      "year": 2021,
      "art": "https://i.scdn.co/image/ab67616d0000b273904fe424f01b15dec51216dc",
      "spotify": "https://open.spotify.com/album/7Gp8zbyNj6r9lm4Bco7CgK",
      "type": "single"
    },
    {
      "id": "r-902550",
      "title": "Hotter Than a Bullet",
      "artist": "Abel.",
      "year": 2021,
      "art": "https://i.scdn.co/image/ab67616d0000b2733013af7ff308ade0e293d473",
      "spotify": "https://open.spotify.com/album/3K2bT9PqZa4Hy1g2EFNei3",
      "type": "single"
    },
    {
      "id": "r-139302",
      "title": "deathwish",
      "artist": "dane",
      "year": 2021,
      "art": "https://i.scdn.co/image/ab67616d0000b2730eee63d03041e510a9b45a7c",
      "spotify": "https://open.spotify.com/album/0oj0mN2K5bV2dOLnXLAKek",
      "type": "single"
    },
    {
      "id": "r-838982",
      "title": "Serotonin (Melatonin Remix)",
      "artist": "Courtney Govan and Abel.",
      "year": 2021,
      "art": "https://i.scdn.co/image/ab67616d0000b273f0bda0049b877a191706a337",
      "spotify": "https://open.spotify.com/album/0cbF7r7oTJwOEDxgSAZIQ2",
      "type": "single"
    },
    {
      "id": "r-516480",
      "title": "For Myself",
      "artist": "Pool Surfers",
      "year": 2021,
      "art": "https://i.scdn.co/image/ab67616d0000b2735d5aab541e698664be10f435",
      "spotify": "https://open.spotify.com/album/2tUSKn7hGIKQgLbRkbxYec",
      "type": "single"
    },
    {
      "id": "r-181087",
      "title": "Radio Silence",
      "artist": "Lily Lewis",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b273fd034b7920cd39d6f5099524",
      "spotify": "https://open.spotify.com/album/1biVTSi4ZalLK3Z95yU6dx",
      "type": "single"
    },
    {
      "id": "r-513699",
      "title": "pay for me",
      "artist": "dane",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b273aaa38956a23a4f0a02ad7c1c",
      "spotify": "https://open.spotify.com/album/5AuYapJdtw9JxXwiJp0riL",
      "type": "single"
    },
    {
      "id": "r-295977",
      "title": "die in love & live forever",
      "artist": "Dane",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b273686d88c54093f2ecfbd807e5",
      "spotify": "https://open.spotify.com/album/0k7M47D1kzEV4iP4rexgik",
      "type": "single"
    },
    {
      "id": "r-343383",
      "title": "didn't know a thing (feat. HUSH)",
      "artist": "Dane",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b2732861fda7313298217272a870",
      "spotify": "https://open.spotify.com/album/33KA2R4DImrwqcoRhBZ7LL",
      "type": "single"
    },
    {
      "id": "r-889838",
      "title": "modern classic",
      "artist": "Dane",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b27370ba29a1ebef2838065401c1",
      "spotify": "https://open.spotify.com/album/5EM8ENPUEtLB7y6u8B2quy",
      "type": "single"
    },
    {
      "id": "r-911609",
      "title": "reset/rewind (feat. Abel.)",
      "artist": "Dane",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b27309f90f772fba2bac1756bbbc",
      "spotify": "https://open.spotify.com/album/1JugwlnSg0OrGUUG1ogilE",
      "type": "single"
    },
    {
      "id": "r-796069",
      "title": "better together",
      "artist": "Dane",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b273f069b271cbed3293a0aff366",
      "spotify": "https://open.spotify.com/album/0ia6kmL4GZHrb0f1vbYvKF",
      "type": "single"
    },
    {
      "id": "r-180303",
      "title": "K-Hole",
      "artist": "Hush",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b273e9068494f4729b4c589fc3da",
      "spotify": "https://open.spotify.com/album/09LjTWLaCSvlW2yLAx4EAy",
      "type": "EP",
      "tracks": [
        "Pulled Up On",
        "K-Hole"
      ]
    },
    {
      "id": "r-567128",
      "title": "",
      "artist": "Abel.",
      "year": 2020,
      "art": "",
      "spotify": "",
      "type": "EP",
      "tracks": [
        "Nightowl",
        "Comfortable"
      ]
    },
    {
      "id": "r-996070",
      "title": "Hush Puppies",
      "artist": "Hush",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b27309020f70cf1e483b2f103365",
      "spotify": "https://open.spotify.com/album/0gRQptCE31MNxLxIO9wBf8",
      "type": "EP",
      "tracks": [
        "Dab Queen",
        "Scotch",
        "Eyeballs"
      ]
    },
    {
      "id": "r-449978",
      "title": "Collars",
      "artist": "Pool Surfers",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b2737341d95f62d2559bb1b3774b",
      "spotify": "https://open.spotify.com/album/15IHEizGxQd6pEVoVznqb4",
      "type": "single"
    },
    {
      "id": "r-974637",
      "title": "Portray",
      "artist": "Pool Surfers",
      "year": 2020,
      "art": "https://i.scdn.co/image/ab67616d0000b2731077d696542cad30d92a6a4d",
      "spotify": "https://open.spotify.com/album/059P3jZhP8xgaKKqJMGUkM",
      "type": "single"
    },
    {
      "id": "r-544901",
      "title": "something left to be said",
      "artist": "dane",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b273a2d690f0dcd8245fd70fdb36",
      "spotify": "https://open.spotify.com/album/3z1powOtQWZ4y0DQN5kJCX",
      "type": "single"
    },
    {
      "id": "r-584549",
      "title": "Sugar",
      "artist": "Hush",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b27331e0ecfc37b9d6fe41398783",
      "spotify": "https://open.spotify.com/album/1b3OHmkSpM9f0iWmRyXeU6",
      "type": "single"
    },
    {
      "id": "r-951417",
      "title": "You're Not Who You Used to Be",
      "artist": "Van Alden",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b27397d87c1ada5e2a8fc23cccf0",
      "spotify": "https://open.spotify.com/album/2bjB1EivO4B2BxSebH56X9",
      "type": "EP",
      "tracks": [
        "xo",
        "Forever",
        "Foolish",
        "Stay",
        "You're Not Who You Used to Be"
      ]
    },
    {
      "id": "r-573598",
      "title": "listen!",
      "artist": "dane",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b273af7a3b16b62cef1ab2eb9f60",
      "spotify": "https://open.spotify.com/album/2GZgTm1Ml7VoXh1DoaGu8N",
      "type": "single"
    },
    {
      "id": "r-672814",
      "title": "nothing but forbidden fruit",
      "artist": "Abel.",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b2732d340545b86c929460f083b1",
      "spotify": "https://open.spotify.com/album/3Pwe0BXl1qoFP0x1LrEpsa",
      "type": "album",
      "tracks": [
        "Earth Laughs",
        "Kissing Mary",
        "Consequences",
        "if i were to follow you",
        "In Flowers",
        "My Fault"
      ]
    },
    {
      "id": "r-583559",
      "title": "5150",
      "artist": "Pool Surfers",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b2738ff85789d82b3793379e93e4",
      "spotify": "https://open.spotify.com/album/2rT6zc6qrumdhHDIDNWy94",
      "type": "single"
    },
    {
      "id": "r-071131",
      "title": "Indulge",
      "artist": "Pool Surfers",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b2731439d20d69a2d484c857e736",
      "spotify": "https://open.spotify.com/album/3h4HHPLA6RQGqtcZBYzq7d",
      "type": "single"
    },
    {
      "id": "r-229532",
      "title": "Rollar Coaster (Live at Dramakaze)",
      "artist": "Pool Surfers",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b273e5cc86330fabcfad78494abf",
      "spotify": "https://open.spotify.com/album/6SGCvps469mT0gpfyJbWAH",
      "type": "album",
      "tracks": [
        "Acid",
        "Unfold",
        "Elvira",
        "Not to Mention",
        "Roller Coaster",
        "Bleed Blue"
      ]
    },
    {
      "id": "r-727810",
      "title": "Cycle",
      "artist": "Hush",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b2733aaea40db72f41b76e93503b",
      "spotify": "https://open.spotify.com/album/1Tnqfnvv30MbFks1KFSS6x",
      "type": "single"
    },
    {
      "id": "r-243706",
      "title": "Caught Up",
      "artist": "Pool Surfers",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b2739b2dab6ecba27649d7b1b4ff",
      "spotify": "https://open.spotify.com/album/1LuQxb56qFFbmzhSNWifeV",
      "type": "single"
    },
    {
      "id": "r-188281",
      "title": "Get a Ride",
      "artist": "Hush",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b2730092719c02baa44552c28d7e",
      "spotify": "https://open.spotify.com/album/3Hpacjh3VdYrYnSXZabzB8",
      "type": "single"
    },
    {
      "id": "r-673361",
      "title": "nothing but forbidden fruit",
      "artist": "Abel.",
      "year": 2019,
      "art": "https://i.scdn.co/image/ab67616d0000b2732d340545b86c929460f083b1",
      "spotify": "https://open.spotify.com/album/3Pwe0BXl1qoFP0x1LrEpsa",
      "type": "EP",
      "tracks": [
        "Earth Laughs",
        "Consequences",
        "My Fault"
      ]
    },
    {
      "id": "r-341313",
      "title": "Van Alden",
      "artist": "Van Alden",
      "year": 2018,
      "art": "https://i.scdn.co/image/ab67616d0000b273397941e895a2303d54ff3a7c",
      "spotify": "https://open.spotify.com/album/09KPdfjxZLq4FV33F0YC3k",
      "type": "album",
      "tracks": [
        "Boheme",
        "Sinners",
        "Never Die",
        "Otherside",
        "an(otherside)",
        "Van Alden"
      ]
    },
    {
      "id": "r-249595",
      "title": "Take Us Alive (feat. Lovergirl)",
      "artist": "Hush",
      "year": 2018,
      "art": "https://i.scdn.co/image/ab67616d0000b2738de649b39a5f9c295d8ac615",
      "spotify": "https://open.spotify.com/album/3CPuskKv0eRSrxwrEiR0AH",
      "type": "single"
    },
    {
      "id": "r-456740",
      "title": "Wasted (On Me)",
      "artist": "Hush",
      "year": 2018,
      "art": "https://i.scdn.co/image/ab67616d0000b273b4a57275f824cfdf4912ffeb",
      "spotify": "https://open.spotify.com/album/6af5YKV1oU2Ooyge5SmBQJ",
      "type": "single"
    },
    {
      "id": "r-242404",
      "title": "D E E P R E S T",
      "artist": "Dane Christopher",
      "year": 2018,
      "art": "https://i.scdn.co/image/ab67616d0000b273279b1bf8989cc61ccafee479",
      "spotify": "https://open.spotify.com/album/0VGK9EJoU1Mr89BZEYh7Wc",
      "type": "single"
    },
    {
      "id": "r-840556",
      "title": "My Fault",
      "artist": "Abel.",
      "year": 2018,
      "art": "https://i.scdn.co/image/ab67616d0000b273061482376b3903a82dc1bdf5",
      "spotify": "https://open.spotify.com/album/4qNGgUOPDbnSkevWl7CaVf",
      "type": "single"
    },
    {
      "id": "r-743353",
      "title": "A Concept of Corners",
      "artist": "My Native Tongue",
      "year": 2018,
      "art": "https://i.scdn.co/image/ab67616d0000b273a5e16fab12b88ddeca6a48fa",
      "spotify": "https://open.spotify.com/album/4WTRfl57HpD3kfiLmgN013",
      "type": "single"
    },
    {
      "id": "bc-2139484342",
      "title": "Sink Swim x Compare/Contrast Split (Question Everything)",
      "artist": "Sink Swim",
      "year": 2013,
      "art": "https://f4.bcbits.com/img/a1739733182_5.jpg",
      "spotify": "",
      "bandcamp": "2139484342",
      "type": "album",
      "tracks": [
        "The Fade",
        "Flee This Smallest City",
        "Dispel feat. Fabi Behnam",
        "Sink Swim x Compare/Contrast - Interlude (Question Everything)",
        "Compare/Contrast - Inference",
        "Compare/Contrast - Porcelain Wings",
        "Compare/Contrast - Interpellation feat. Dane Petersen"
      ]
    },
    {
      "id": "bc-1284709978",
      "title": "Heights",
      "artist": "Sink Swim",
      "year": 2013,
      "art": "https://f4.bcbits.com/img/a3469222587_5.jpg",
      "spotify": "",
      "bandcamp": "1284709978",
      "type": "EP",
      "tracks": [
        "Tides",
        "Move Me",
        "Perfect On Paper",
        "Pull Together ft. Alexa San Roman",
        "Heights"
      ]
    },
    {
      "id": "bc-797836521",
      "title": "Elements - EP",
      "artist": "Sink Swim",
      "year": 2012,
      "art": "https://f4.bcbits.com/img/a0094809508_5.jpg",
      "spotify": "",
      "bandcamp": "797836521",
      "type": "EP",
      "tracks": [
        "Beneath Our Sleeves",
        "Losing Sleep",
        "Elements",
        "Breeze",
        "Last Year"
      ]
    }
  ],
  "studio": [
    {
      "client": "Mitchell Dolphin",
      "title": "Drop the Ball",
      "role": "Produced",
      "year": 2026,
      "link": "https://open.spotify.com/album/3HyfMyPFa1smut151Zpj6i"
    },
    {
      "client": "Harrison Borts",
      "title": "spin",
      "role": "Produced",
      "year": 2025,
      "link": "https://open.spotify.com/album/751Iml250lmKBFcFRpEXax"
    },
    {
      "client": "Mitchell Dolphin",
      "title": "Once Again",
      "role": "Produced",
      "year": 2025,
      "link": "https://open.spotify.com/album/26uWKSSQ741ry2EtKsgeno"
    },
    {
      "client": "The Artist Ren",
      "title": "willow tree",
      "role": "Produced",
      "year": 2025,
      "link": "https://open.spotify.com/album/7z8PDSmqebIj5QWiryGOa1"
    },
    {
      "client": "The Artist Ren",
      "title": "Runway",
      "role": "Produced",
      "year": 2024,
      "link": "https://open.spotify.com/album/3VS81WgvgXM99ySFNtJgZY"
    },
    {
      "client": "The Artist Ren",
      "title": "cloudynight",
      "role": "Produced",
      "year": 2024,
      "link": "https://open.spotify.com/album/3Yhto188w6UDqwMsEx9ZKe"
    },
    {
      "client": "abeltriesherbest",
      "title": "porsche pastor",
      "role": "Produced",
      "year": 2023,
      "link": "https://open.spotify.com/album/3w9cDHl5Sc9VE8GTMuEHVd"
    },
    {
      "client": "abeltriesherbest",
      "title": "what if i were to tell you that... (audio movie)",
      "role": "Produced",
      "year": 2023,
      "link": "https://open.spotify.com/album/6guHhGU1hKCtVkZneGM4A0"
    },
    {
      "client": "Abel.",
      "title": "shower boy",
      "role": "Produced",
      "year": 2022,
      "link": "https://open.spotify.com/album/0pLa6IWRykFdlFV9czgIkf"
    },
    {
      "client": "Abel.",
      "title": "songs from the big dumpster",
      "role": "Produced",
      "year": 2022,
      "link": "https://open.spotify.com/album/1Y2boLHJ17Yx7OD8igxTGk"
    },
    {
      "client": "Sleeptalk",
      "title": "Drown in a Rainbow (Deluxe Edition)",
      "role": "Produced",
      "year": 2022,
      "link": "https://open.spotify.com/album/1EnECc1PMYmkAKTsY7Aovd"
    },
    {
      "client": "Stun Gun",
      "title": "Put er Down",
      "role": "Produced",
      "year": 2022,
      "link": "https://open.spotify.com/album/5ULL5lK6RUB6jcEtnpD9QK"
    },
    {
      "client": "xglypretty",
      "title": "hands off the kids",
      "role": "Produced",
      "year": 2022,
      "link": "https://open.spotify.com/album/2CjyhmKTL4Gn1IjP7fKxAX"
    },
    {
      "client": "xglypretty",
      "title": "souled out",
      "role": "Produced",
      "year": 2022,
      "link": "https://open.spotify.com/album/4Kt4cTs6Vcwr3AyFxPxVI8"
    },
    {
      "client": "xglypretty",
      "title": "bad christian, music",
      "role": "Produced",
      "year": 2022,
      "link": "https://open.spotify.com/album/4ewFmSo8cm5kjRaHeO6KXl"
    },
    {
      "client": "Abel.",
      "title": "Hotter Than a Bullet",
      "role": "Produced",
      "year": 2021,
      "link": "https://open.spotify.com/album/3K2bT9PqZa4Hy1g2EFNei3"
    },
    {
      "client": "Abel.",
      "title": "Can't Love You the Way I Hate You",
      "role": "Produced",
      "year": 2021,
      "link": "https://open.spotify.com/album/7Gp8zbyNj6r9lm4Bco7CgK"
    },
    {
      "client": "dane",
      "title": "deathwish",
      "role": "Produced",
      "year": 2021,
      "link": "https://open.spotify.com/album/0oj0mN2K5bV2dOLnXLAKek"
    },
    {
      "client": "dane",
      "title": "better together",
      "role": "Produced",
      "year": 2020,
      "link": "https://open.spotify.com/album/0ia6kmL4GZHrb0f1vbYvKF"
    },
    {
      "client": "dane",
      "title": "pay for me",
      "role": "Produced",
      "year": 2020,
      "link": "https://open.spotify.com/album/5AuYapJdtw9JxXwiJp0riL"
    },
    {
      "client": "dane",
      "title": "didn't know a thing",
      "role": "Produced",
      "year": 2020,
      "link": "https://open.spotify.com/album/33KA2R4DImrwqcoRhBZ7LL"
    },
    {
      "client": "Deadskull",
      "title": "66S",
      "role": "Produced",
      "year": 2020,
      "link": "https://open.spotify.com/album/0lzDRpggefSXZny7ZTYgX2"
    },
    {
      "client": "Deadskull",
      "title": "DOOM",
      "role": "Produced",
      "year": 2020,
      "link": "https://open.spotify.com/album/2gjrnL7yw5831DscjEgzsP"
    },
    {
      "client": "Deadskull",
      "title": "HO WAIT",
      "role": "Produced",
      "year": 2020,
      "link": "https://open.spotify.com/album/2WoG5OR78r0HV27WBC12gg"
    },
    {
      "client": "Abel.",
      "title": "nothing but forbidden fruit",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/3Pwe0BXl1qoFP0x1LrEpsa"
    },
    {
      "client": "dane",
      "title": "something left to be said",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/3z1powOtQWZ4y0DQN5kJCX"
    },
    {
      "client": "dane",
      "title": "listen!",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/2GZgTm1Ml7VoXh1DoaGu8N"
    },
    {
      "client": "HUSH",
      "title": "Sugar",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/1b3OHmkSpM9f0iWmRyXeU6"
    },
    {
      "client": "HUSH",
      "title": "Get a Ride",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/3Hpacjh3VdYrYnSXZabzB8"
    },
    {
      "client": "HUSH",
      "title": "Cycle",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/1Tnqfnvv30MbFks1KFSS6x"
    },
    {
      "client": "Pool Surfers",
      "title": "Indulge",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/3h4HHPLA6RQGqtcZBYzq7d"
    },
    {
      "client": "Pool Surfers",
      "title": "5150",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/2rT6zc6qrumdhHDIDNWy94"
    },
    {
      "client": "Pool Surfers",
      "title": "Caught Up",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/1LuQxb56qFFbmzhSNWifeV"
    },
    {
      "client": "Private Island",
      "title": "5xx",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/6I1mB6BhE5VpSb9bzI0WYw"
    },
    {
      "client": "Van Alden",
      "title": "You're Not Who You Used to Be",
      "role": "Produced",
      "year": 2019,
      "link": "https://open.spotify.com/album/2bjB1EivO4B2BxSebH56X9"
    },
    {
      "client": "Abel.",
      "title": "Consequences",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/7hMzWuAzvDil4jRf5KBBUQ"
    },
    {
      "client": "Abel.",
      "title": "Earth Laughs",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/7BS0kcTwspytsi47tYgIYZ"
    },
    {
      "client": "Abel.",
      "title": "My Fault",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/4qNGgUOPDbnSkevWl7CaVf"
    },
    {
      "client": "dane christopher",
      "title": "T H R O U G H",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/7AXHFb2Tmf8MvzEZApN9dG"
    },
    {
      "client": "dane christopher",
      "title": "D E E P R E S T",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/0VGK9EJoU1Mr89BZEYh7Wc"
    },
    {
      "client": "dane christopher",
      "title": "A N T I - S O C I A L B U T T E R F L Y",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/6HpkhRMkheba7mRDZhab8T"
    },
    {
      "client": "HUSH",
      "title": "Easy",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/0WThQLqsOsM4A15K2pxjOV"
    },
    {
      "client": "HUSH",
      "title": "Take Us Alive",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/3CPuskKv0eRSrxwrEiR0AH"
    },
    {
      "client": "HUSH",
      "title": "Ritual",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/2rYkOmGydEcB1AX6aFP1zL"
    },
    {
      "client": "HUSH",
      "title": "Wasted (On Me)",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/6af5YKV1oU2Ooyge5SmBQJ"
    },
    {
      "client": "Pool Surfers",
      "title": "Loose Life",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/4uH0iAeNE2JwLrTIiW3uMn"
    },
    {
      "client": "Pool Surfers",
      "title": "Lucid",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/1J7Cc2pAxCiVOQgTTpkJjd"
    },
    {
      "client": "Sleeptalk",
      "title": "I Hope You're Doing Well",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/0wJSQycGMeRxMqvIc84RLP"
    },
    {
      "client": "Van Alden",
      "title": "Boheme",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/0gpGB3VvAywV0L1rwXAz1Q"
    },
    {
      "client": "Van Alden",
      "title": "Otherside",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/5jMGZ0bL1VNlgl8YUPRgYG"
    },
    {
      "client": "Van Alden",
      "title": "Van Alden",
      "role": "Produced",
      "year": 2018,
      "link": "https://open.spotify.com/album/09KPdfjxZLq4FV33F0YC3k"
    },
    {
      "client": "HUSH",
      "title": "Waves",
      "role": "Produced",
      "year": 2017,
      "link": "https://open.spotify.com/album/7A5uQmLEeQd1s0I9iXjrWn"
    },
    {
      "client": "My Native Tongue",
      "title": "Lamplight",
      "role": "Produced",
      "year": 2017,
      "link": "https://open.spotify.com/album/3BgvDkjlIYqksb2UGmZdh3"
    },
    {
      "client": "Private Island",
      "title": "Sunbreak",
      "role": "Produced",
      "year": 2016,
      "link": "https://open.spotify.com/album/7vsK7LO5pg9tX3FdlrGPM5"
    },
    {
      "client": "Private Island",
      "title": "Drugs",
      "role": "Produced",
      "year": 2016,
      "link": "https://open.spotify.com/album/5oD2h9PoO5CI4VU26HS22Z"
    },
    {
      "client": "My Native Tongue",
      "title": "Plane Kids",
      "role": "Produced",
      "year": 2015,
      "link": "https://open.spotify.com/album/2yBlv5Ee5jo7Thebo3OBmW"
    },
    {
      "client": "The Royal Sound",
      "title": "Mother",
      "role": "Produced",
      "year": 2015,
      "link": "https://open.spotify.com/album/2hhbQNiGUwiWBG7SMb0oAQ"
    },
    {
      "client": "Private Island",
      "title": "A Good Look",
      "role": "Produced",
      "year": 2014,
      "link": "https://open.spotify.com/album/1k1SrYt2GsZQubvKilvMfi"
    }
  ]
};
